apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cncf-1
  namespace: argocd
  labels:
    backstage.io/kubernetes-id: demo-cncf-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/scaffolder-lab/demo-cncf-1.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
